### ISSUE TITLE
SSL CERTIFICATE_VERIFY_FAILED: cannot download files in dataset, branch frgfm/dataset_draft 

### ISSUE THREAD

**Issue by blenzi** [pyronear/pyro-vision#12] opened 2019-10-02 17:48 UTC
## 🐛 Bug

Running locally, SSL CERTIFICATE_VERIFY_FAILED: cannot download files in dataset

## To Reproduce

1. Checkout locally branch frgfm/dataset_draft 
2. Create OpenFire object 

```
git remote add upstream git@github.com:frgfm/PyroNear.git
git checkout -t upstream/dataset_draft
python -c "from pyronear.datasets import OpenFire; dataset = OpenFire(root='./data', download=True)"
```

## Expected behavior

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/frgfm/PyroNear/master/pyronear/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/frgfm/PyroNear/master/pyronear/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: None
Torchvision version: 0.4.0

OS: Mac OSX 10.13.4
GCC version: Could not collect
CMake version: version 3.6.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0
[conda] Could not collect

**Comment by blenzi** [comment] 2019-10-02 19:23
The problem seems to be related to *https* links as described in https://legacy.python.org/dev/peps/pep-0476/. 

As described in  https://legacy.python.org/dev/peps/pep-0476/#opting-out  "It is also possible, though highly discouraged":
```
import ssl; ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by frgfm** [comment] 2019-10-12 10:51
As I am unable to reproduce on various environments and since it looks like an environment-related issue, I'm closing the issue!

Feel free to reopen it if you think it is related to this repo.

**Closed as completed by frgfm** 2019-10-12 10:51 UTC
Labels: type: bug, help wanted, wontfix

**Comment by blenzi** [comment] 2019-10-15 13:19
The solution was to upgrade the ```certifi``` package as described in
https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org
